var SV=window.SV||{};SV.AlertImprovements=SV.AlertImprovements||{};
(function(c,k,l,m){SV.AlertImprovements.updateAlert=function(a,b,c,e){var d=a.hasClass("is-unread");a.removeClass("is-read");d?a.addClass("is-recently-read").removeClass("is-unread"):a.removeClass("is-recently-read").addClass("is-unread");(d=a.data("alertId"))?(b=b.find("[data-alert-id='"+d+"']"),b.length&&(c&&b.find(e).remove(),XF.setupHtmlInsert(b,function(b,c,d){a.empty();a.append(b.children())}))):(a.find(".alert--unsummarize").remove(),a.find(".alert--mark-read").remove(),a.find(".alert--mark-unread").remove())};
SV.AlertImprovements.AlertToggler=XF.Event.newHandler({eventNameSpace:"SVAlertImprovementsAlertTogglerClick",eventType:"click",options:{inListSelector:".contentRow-figure--selector",successMessageFlashTimeOut:3E3},processing:null,init:function(){this.processing=!1},click:function(a){a.preventDefault();if(!this.processing){this.processing=!0;var b=this;a=this.$target;var f=0<a.closest(".js-alert").find(this.options.inListSelector).length;XF.ajax("POST",a.attr("href"),{inlist:f?1:0},c.proxy(this,"handleMarkReadAjax")).always(function(){b.processing=
!1})}},handleMarkReadAjax:function(a){a.message&&XF.flashMessage(a.message,this.options.successMessageFlashTimeOut);var b=this.$target.closest(".js-alert"),f=!b.find(this.options.inListSelector).length,e=this.options.inListSelector;a=a.html&&a.html.content?c(a.html.content):c("<div/>");SV.AlertImprovements.updateAlert(b,a,f,e)}});SV.AlertImprovements.BulkMarkRead=XF.Event.newHandler({eventNameSpace:"SVAlertImprovementsAlertListMarkReadClick",eventType:"click",options:{successMessageFlashTimeOut:3E3,
inListSelector:".contentRow-figure--selector",alertItemSelector:".js-alert.is-unread"},processing:null,init:function(){this.processing=!1},click:function(a){a.preventDefault();if(!this.processing){this.processing=!0;var b=this,f=this.options.inListSelector;a=this.$target;var e={},d=[],h={},g=[];XF.findRelativeIf(this.options.alertItemSelector,this.$target).each(function(){var a=c(this),b=a.data("alertId");a=0<a.find(f).length;b&&(a?b in e||(e[b]=1,d.push(b)):b in h||(h[b]=1,g.push(b)))});d.length&&
XF.ajax("POST",a.attr("href"),{inlist:1,alert_ids:d},c.proxy(this,"handleMarkAllReadAjaxList")).always(function(){b.processing=!1});g.length&&XF.ajax("POST",a.attr("href"),{inlist:0,alert_ids:g},c.proxy(this,"handleMarkAllReadAjaxPopup")).always(function(){b.processing=!1});d.length||g.length||(this.processing=!1)}},handleMarkAllReadAjaxList:function(a){this.handleMarkAllReadAjax(a,!0)},handleMarkAllReadAjaxPopup:function(a){this.handleMarkAllReadAjax(a,!1)},handleMarkAllReadAjax:function(a,b){a.message&&
XF.flashMessage(a.message,this.options.successMessageFlashTimeOut);var f=a.html&&a.html.content?c(a.html.content):c("<div/>"),e=this.options.inListSelector,d=!b;a.html.content="<div/>";XF.setupHtmlInsert(a.html,function(a,b,c){});XF.findRelativeIf(this.options.alertItemSelector,this.$target).each(function(){SV.AlertImprovements.updateAlert(c(this),f,d,e)})}});SV.AlertImprovements.AlertUnsummarize=XF.Event.newHandler({eventNameSpace:"SVAlertImprovementsAlertUnsummarizeClick",eventType:"click",options:{alertPopupSelector:".p-navgroup-link--alerts",
successMessageFlashTimeOut:3E3},processing:null,init:function(){this.processing=!1},click:function(a){a.preventDefault();this.processing||(this.processing=!0,XF.ajax("POST",this.$target.attr("href"),{},c.proxy(this,"handleReloadAlertsPopupList")).always(function(){self.processing=!1}))},handleReloadAlertsPopupList:function(a){a.message&&XF.flashMessage(a.message,this.options.successMessageFlashTimeOut);(a=this.$target.closest(".js-alert").data("alertId"))&&c(".js-alert[data-alert-id='"+a+"']").remove()}});
XF.Click.register("sv-mark-alerts-read","SV.AlertImprovements.BulkMarkRead");XF.Click.register("mark-alert-unread","SV.AlertImprovements.AlertToggler");XF.Click.register("unsummarize-alert","SV.AlertImprovements.AlertUnsummarize")})(jQuery,window,document);
